# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TensorTS": "80_timeseries_core.ipynb",
         "ToTensorTS": "80_timeseries_core.ipynb",
         "LabelTS": "80_timeseries_core.ipynb",
         "get_stats": "80_timeseries_core.ipynb",
         "Normalize": "80_timeseries_core.ipynb",
         "SelfNormalize": "80_timeseries_core.ipynb",
         "default_show_batch": "80_timeseries_core.ipynb",
         "TSData": "80_timeseries_data.ipynb",
         "show_timeseries": "80_timeseries_data.ipynb",
         "download_unzip_data": "80_timeseries_data.ipynb",
         "unzip": "80_timeseries_data.ipynb",
         "download_unzip_data_UCR": "80_timeseries_data.ipynb",
         "get_UCR_univariate_list": "80_timeseries_data.ipynb",
         "get_UCR_multivariate_list": "80_timeseries_data.ipynb"}

modules = ["core.py",
           "tsdata.py"]

doc_url = "https://ai-fast-track.github.io/timeseries/"

git_url = "https://github.com/ai-fast-track/timeseries/tree/master/"

def custom_doc_links(name): return None
