# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TSData": "80_timeseries_data.ipynb",
         "get_ts_items": "80_timeseries_data.ipynb",
         "show_timeseries": "80_timeseries_data.ipynb",
         "download_unzip_data": "80_timeseries_data.ipynb",
         "unzip": "80_timeseries_data.ipynb",
         "download_unzip_data_UCR": "80_timeseries_data.ipynb",
         "URLs_TS": "80_timeseries_data.ipynb",
         "get_UCR_univariate_list": "80_timeseries_data.ipynb",
         "get_UCR_multivariate_list": "80_timeseries_data.ipynb",
         "test_eq_tensor": "81_timeseries_core.ipynb",
         "TensorTS": "81_timeseries_core.ipynb",
         "ToTensorTSBlock": "81_timeseries_core.ipynb",
         "ToTensorTS": "81_timeseries_core.ipynb",
         "LabelTS": "81_timeseries_core.ipynb",
         "get_min_max": "81_timeseries_core.ipynb",
         "get_mean_std": "81_timeseries_core.ipynb",
         "Standardize": "81_timeseries_core.ipynb",
         "Normalize": "81_timeseries_core.ipynb",
         "TSBlock": "81_timeseries_core.ipynb",
         "default_show_batch": "81_timeseries_core.ipynb",
         "TSDataLoaders": "81_timeseries_core.ipynb",
         "get_n_channels": "81_timeseries_core.ipynb"}

modules = ["data.py",
           "core.py"]

doc_url = "https://ai-fast-track.github.io/timeseries/"

git_url = "https://github.com/ai-fast-track/timeseries/tree/master/"

def custom_doc_links(name): return None
